# Number of the dataset
dataset_number: 40000
# Events generated for each file
n_events_per_run: 1000
# Number of total runs/file
n_runs: 1000

# Pattern for the outputfile
output_pattern: '{run_folder}/Level0.{step}_track_snowstorm_IC86.2012_pass2.{dataset_number:6d}.{run_number}.i3.bz2'
# sub-dict to indicate need resources
resources:
  # Indication which steps need GPUs, default is 0
  gpus:
    1: 1
  # Indication of needed memory for each step if nothing is set 1GB is assumed as default
  memory:
    1: 6gb
    2: 5gb
    3: 3gb
    13: 3gb
    23: 3gb
    33: 3gb
  # Indication of the walltime (in hours) for each step, if nothing is set the system default for dagman and 1h for pbs are assumed
  walltime:
  # Indication of the number of cores for each step, default is 1
  cpus:
    1: 1

# Dagman options
dagman_max_jobs: 5000
dagman_submits_interval: 500
dagman_scan_interval: 1
dagman_submit_delay: 0


# Options used in the steps
# Options that are expected to be set to generate the scripts
seed: 1337
# Whether file after IceTray should be kept
keep_crashed_files: 0
# If True: use I3GSLRandomService, otherwise use I3SPRNGRandomService
# (Newer cmvfs python and icecube builds do not have I3SPRNGRandomService)
random_service_use_gslrng: True

# PATH to the GCD File
gcd: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2020.Run134142.Pass2_V0.i3.gz
gcd_pass2: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2020.Run134142.Pass2_V0.i3.gz

# -------------------------
# Step 0: track Injection
# -------------------------
# track Generation specific settings
# Energy range for track
track_energy_range: [!!float 1e2, !!float 1e8]
# Zenith range of track in degrees
zenith_range: [0., 180.]
# Azimuth range of track in degrees
azimuth_range: [0., 360.]
# sample direction uniformly on sphere
sample_uniformly_on_sphere: True
# entry time range in ns [min,max]
time_range: [0,0]
# anchor range in m [min,max]
x_range: [-700,700]
y_range: [-700,700]
z_range: [-700,700]
# Injection sphere radius in meters
injection_sphere_radius: 750
# Maximum Distance of anchor to convex hull around IceCube
max_anchor_distance: 100
# oversampling to use
oversampling_factor:
# oversample after proposal or before?
oversample_after_proposal: False
# keep keys for merging of oversampled events
oversampling_keep_keys: []
# additional keywords for the track generation
track_injection_kwargs: {}

# Distance splits are not available for snowstorm chain
distance_splits:
threshold_doms:
oversize_factors:

# -----------------------------
# Step 1: Snowstorm Propagation
# -----------------------------
NumEventsPerModel: 100
DOMOversizeFactor: 1.
UseI3PropagatorService: True
UseGPUs: True
SummaryFile:

# These arguments will be passed on to the CLSIM Client Module
ExtraArgumentsToI3CLSimClientModule:
  # Sources with no DOMs within this distance (meter) are *not* simulated
  ClosestDOMDistanceCutoff: 500.

snowstorm_config:
  # Config for the full-scale systematics dataset
  # (after alignment with the calibration group)
  # baseline ice-model and hole-ice parametrization
  IceModelLocation: "$I3_BUILD/ice-models/resources/models/ICEMODEL/spice_ftp-v3m"
  HoleIceParameterization: "$I3_BUILD/ice-models/resources/models/ANGSENS/angsens_unified/as.set2_p0=0.28_p1=-0.075"
  # Control ice model perturbations:
  Perturbations:
      # IceWavePlusModes for depth dependent absorption/scattering scaling
      IceWavePlusModes:
          apply: False
          type: default
      # Global ice scattering scaling
      Scattering:
          type: uniform
          uniform:
              limits: [[0.913, 1.087]]
      # Global ice absorption scaling
      Absorption:
          type: uniform
          uniform:
              limits: [[0.913, 1.087]]
      # # DOM efficiency scaling
      # DOMEfficiency:
      #     type: uniform
      #     uniform:
      #         limits: [[1.0, 1.0]]

      # DOM angular acceptance according to the Unified HoleIce model
      # see: https://github.com/philippeller/angular_acceptance
      HoleIceForward_Unified:
          type: uniform
          uniform:
              limits: [[-0.1, 0.5], [-0.1, 0.0]]
              # limits: [[0.28, 0.28], [-0.075, -0.075]]
              # limits: [[0.25, 0.25], [-0.06, -0.06]]

# -----------------------------
# Step 2: Detector Simulation
# -----------------------------
# Remove this list of keys from the M-Frames
det_remove_keys_from_m_frame: [
    'AngularAcceptance',
    'MediumProperties',
    'WavelengthAcceptance',
    'WavelengthGenerationBias',
]
# keep MCPEs in frame
det_keep_mc_hits: False
# keep I3MCPulseSeriesMap in frame.
det_keep_mc_pulses: False
# keep MCTree with all in-ice propagated secondaries. These take a lot of space compared un propagated tree.
det_keep_propagated_mc_tree: True
# Keep everything upto run X
det_keep_all_upto: -1
# add beacon lauches.
det_add_beacon_launches: True
# reduce peak memory use by repeatedly merging hits as they are generated.  WARNING: Use of this option may slightly reduce precision and drastically increase running time. It is potentially useful for very bright events, and probably harmful for very long events.
det_low_mem: False
# remove events that don't pass any trigger.
det_filter_trigger: True
# do not run Vuvuzela.
det_skip_noise_generation: False
# add noise-free pulses in addition to normal simulation
add_no_noise_pulses: False
# convert I3MCTree to linearized version if True
det_convert_to_linear_tree: True
# If this is a Genie simulation, then this needs to be set to True
det_is_genie_simulation: False
# If this is an IceTop simulation, then this needs to be set to True
det_is_icetop_simulation: False
# DOM Efficiency Resampling
#(If det_dom_eff_resmapling_sample_efficiency is set to 0,
# no resampling will be performed )
det_dom_eff_resmapling_sample_efficiency: 0.
det_dom_eff_resmapling_generated_efficiency: 0.


# ------------------
# Step 3: Get Pulses
# ------------------
# Simplified version of L1 processing

# Keep untriggered events substream and keys
L1_keep_untriggered: True

# any keys to delete from frame
keys_to_delete:
