# Number of the dataset
# dataset_number: 
# Number of total runs/file
n_runs: 1000

# Pattern for the outputfile
output_pattern: '{run_folder}/Level0.{step}_{generator}_IC86.2012_pass2.{dataset_number:6d}.{run_number}.i3.bz2'
# sub-dict to indicate need resources
resources:
  # Indication which steps need GPUs, default is 0
  gpus:
    0: 0
    1: 0
    2: 1
    3: 0
    4: 0
    5: 0
  # Indication of needed memory for each step if nothing is set 1GB is assumed as default
  memory:
    0: 4gb
    1: 5gb
    2: 8gb
    3: 6gb
    4: 6gb
    5: 6gb
  # Indication of the walltime (in hours) for each step, if nothing is set the system default for dagman and 1h for pbs are assumed
  walltime:
  # Indication of the number of cores for each step, default is 1
  cpus:

# Dagman options
dagman_max_jobs: 5000
dagman_submits_interval: 500
dagman_scan_interval: 1
dagman_submit_delay: 0

# Options used in the steps
# Options that are expected to be set to generate the scripts
seed: 1337
# Whether file after IceTray should be kept
keep_crashed_files: 0
# If True: use I3GSLRandomService, otherwise use I3SPRNGRandomService
# (Newer cmvfs python and icecube builds do not have I3SPRNGRandomService)
random_service_use_gslrng: True

# PATH to the GCD File
gcd: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2020.Run134142.Pass2_V0.i3.gz
gcd_pass2: /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_2020.Run134142.Pass2_V0.i3.gz

# Name of the generator; only used for naming of the output folder
generator: corsika

# -------------------------------
# Step 0: Select Neutrino
# -------------------------------

# SelectNeutrino specific options

select_neutrino_cfg:
    #Neutrino is selected with pow(energy [GeV], index)",
    EnergyBiasPowerIndex: 1
    # "Bias ratio for NuE:NuEBar:NuMu:NuMuBar:NuTau:NuTauBar. "
    # ParticleBiases: [1, 1, 1, 1, 1, 1]
    #KeepDarkNeutrinos: false
    #UseZeVForm: false

# NeutrinoGenerator specific options
neutrino_generator_config:
    earth: ["PREM_mmc"]
    material: ["Standard"]
    icecapmodel: "IceSheet"
    simmode: "Detector"
    xsecmodel: "csms_differential_v1.0"
    xsecdir : ""
    propmode: "AutoDetect"
    muonrangeextension: False
    #CylinderRadiusInM: 950
    #CylinderHeightInM: 1900
    ccfactor: 1.0
    ncfactor: 0.0
    grfactor: 0.0

# MuonPropagation specific options
muon_propagation_config : {}

# oversampling to use
# Note: this isn't used here, but enables us to use the get_pulses scripts
oversampling_factor:

# -----------------------------
# Step 1: Snowstorm Propagation
# -----------------------------
NumEventsPerModel: 100
DOMOversizeFactor: 1.
UseI3PropagatorService: False
UseGPUs: True
SummaryFile:

# These arguments will be passed on to the CLSIM Client Module
ExtraArgumentsToI3CLSimClientModule:
  # Sources with no DOMs within this distance (meter) are *not* simulated
  ClosestDOMDistanceCutoff: 500.

# Snowstorm Configuration
snowstorm_config:
  # Config for the full-scale systematics dataset
  # (after alignment with the calibration group)
  # baseline ice-model and hole-ice parametrization
  IceModelLocation: "$I3_BUILD/ice-models/resources/models/ICEMODEL/spice_3.2.1"
  HoleIceParameterization: "$I3_BUILD/ice-models/resources/models/ANGSENS/angsens/as.flasher_p1_0.30_p2_-1"
  # Control ice model perturbations:
  Perturbations:
      # IceWavePlusModes for depth dependent absorption/scattering scaling
      IceWavePlusModes:
          apply: False
          type: default
      # Global ice scattering scaling
      Scattering:
          type: uniform
          uniform:
              limits: [[0.9, 1.1]]
      # Global ice absorption scaling
      Absorption:
          type: uniform
          uniform:
              limits: [[0.9, 1.1]]
      # Ice anisotropy scaling
      AnisotropyScale:
          type: uniform
          uniform:
              limits: [[0., 2.0]]
      # DOM efficiency scaling
      DOMEfficiency:
          type: uniform
          uniform:
              limits: [[0.9, 1.1]]

      # DOM angular acceptance according to the Unified HoleIce model
      # see: https://github.com/philippeller/angular_acceptance
      HoleIceForward_Unified:
          type: uniform
          uniform:
                  limits: [[-0.65, 0.60], [-0.08, 0.08]]


# -----------------------------
# Step 2: Detector Simulation
# -----------------------------
# Remove this list of keys from the M-Frames
det_remove_keys_from_m_frame: [
    'AngularAcceptance',
    'MediumProperties',
    'WavelengthAcceptance',
    'WavelengthGenerationBias',
]
# keep MCPEs in frame
det_keep_mc_hits: False
# keep I3MCPulseSeriesMap in frame.
det_keep_mc_pulses: False
# keep MCTree with all in-ice propagated secondaries. These take a lot of space compared un propagated tree.
det_keep_propagated_mc_tree: True
# Keep everything upto run X
det_keep_all_upto: -1
# add beacon lauches.
det_add_beacon_launches: True
# reduce peak memory use by repeatedly merging hits as they are generated.  WARNING: Use of this option may slightly reduce precision and drastically increase running time. It is potentially useful for very bright events, and probably harmful for very long events.
det_low_mem: False
# remove events that don't pass any trigger.
det_filter_trigger: True
# do not run Vuvuzela.
det_skip_noise_generation: False
# convert I3MCTree to linearized version if True
det_convert_to_linear_tree: True
# If this is a Genie simulation, then this needs to be set to True
det_is_genie_simulation: False
# If this is an IceTop simulation, then this needs to be set to True
det_is_icetop_simulation: False
# DOM Efficiency Resampling
#(If det_dom_eff_resmapling_sample_efficiency is set to 0,
# no resampling will be performed )
det_dom_eff_resmapling_sample_efficiency: 0.
det_dom_eff_resmapling_generated_efficiency: 0.



# ----------
# Step 3: L1
# ----------
# Set the Min Bias prescale to something other than default
L1_min_bias_prescale: !!null
# MC is produced by DOMSimulator (default=False)
L1_2012_dom_simulator: False
# Apply QConverter, use if file is P frame only
L1_2012_qify: False
# Retrigger
L1_2012_retrigger: False
# Run GFU
L1_pass2_run_gfu: true
# Keep untriggered events substream and keys
L1_keep_untriggered: False

additional_keep_keys:
  - I3MCTree_preSampling
  - NuGPrimary

# ----------
# Step 4: L2
# ----------

# Keep all online L2 events or just GFU?
OnlineL2_keep_all_L2: True
# Keep all time residuals per event
OnlineL2_keep_time_residuals: False
